# src/OC/PlatformBundle/Resources/config/routing.yml

oc_platform_home:
    path:      /platform/{page}
    defaults:
        _controller: OCPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*
    
oc_platform_view:
    path:      /platform/advert/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:view
    requirements:
        id: \d+
    
oc_platform_add:
    path:      /platform/add
    defaults:
        _controller: OCPlatformBundle:Advert:add

oc_platform_edit:
    path:      /platform/edit/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:edit
    requirements:
        id: \d+

oc_platform_delete:
    path:      /platform/delete/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:delete
    requirements:
        id: \d+

oc_platform_view_slug:
    path:      /platform/{year}/{slug}.{format}
    defaults:
        _controller: OCPlatformBundle:Advert:viewSlug
        format:      html
    requirements:
        year:   \d{4} #quatre chiffres à la suite
        format: html|xml

hello_the_world:
    path:     /hello-world
    defaults: { _controller: OCPlatformBundle:Advert:index_hello_world_ }
    
bye_the_world:
    path:     /byebye-world
    defaults: { _controller: OCPlatformBundle:Advert:index_bye_world_ }
